# This is the default format.
# For more see: https://github.com/mojombo/jekyll/wiki/Permalinks
permalink: /:categories/:year/:month/:day/:title

exclude: [".rvmrc", ".rbenv-version", "ReadMe.md", "Rakefile", "changelog.md", "License.md"]
highlighter: rouge

# Themes are encouraged to use these universal variables
# so be sure to set them if your theme uses them.
#
title: Josh Gachnang's Blog
author:
  name: Josh Gachnang
  email: josh@servercobra.com
  github: pcsforeducation
  twitter: servercobra
  feedburner: nil

production_url : http://blog.servercobra.com

theme: jekyll-theme-slate